[tool.poetry]
name = "randex"
version = "0.1.0"
description = "Create randomized multiple choice exams using latex."
authors = ["G. Arampatzis <gtarabat@gmail.com>"]
readme = "README.md"
packages = [
  {include = "randex"},
  {include = "scripts"},
]

[tool.poetry.dependencies]
python = "^3.10"
pretty-errors = "^1.2.25"
pyyaml = "^6.0.1"
click = "^8.1.7"
pprintpp = "^0.4.0"
cerberus = "^1.3.5"


[tool.poetry.group.dev.dependencies]
bpython = "^0.24"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
validate = "scripts.validate:main"