name: Ruff Lint

on:
    push:
        paths: ["**.py"]
    pull_request:
        paths: ["**.py"]

jobs:
    ruff:
        name: Run Ruff
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout repository
            uses: actions/checkout@v4

        -   name: Set up Python
            uses: actions/setup-python@v5
            with:
                python-version: "3.11"

        -   name: Install Ruff
            run: pip install ruff==0.12.1

        -   name: Run Ruff
            run: ruff check .
